### ISSUE TITLE
Events Landing Page*

### ISSUE THREAD

**Issue by mongmedia** [YaleDHLab/dhlab-site#10]
![annotated - events](https://user-images.githubusercontent.com/25487/30069041-9b08c322-922d-11e7-893d-c695a3139b68.png)

1) The layout has a header w/ 2 "filters" on the top right. Users can filter events by Type: i.e. Workshops, Talks, Collaborations, Symposia, Conference, etc...we need to determine the common event types/format that we can use to categorize them. It might also be useful to have a filter based on topic, for example, all network analysis related things, or coding workshops. Perhaps the topic filter is powered by a tagging function for each event.

2) The upcoming events listing can show either all our forthcoming event or the first X number of events. Please advise as to how many you want to show. The aspect ratio for events will be square (250 x 250). The rollover state is illustrated by the second event in the comp.

3) On Campus: This is a text-only listing of other events from other center, i.e. CSSSI, StatLab, which are not co-sponsored by DHLab but may be good resources for our audiences. 

4) Past Events: This is a way to list the last few past events so that users can revisit them and click to any documentation that is posted there.

**Comment by duhaime** [comment]
@mongmedia @cderose Should the blurb for each event card be the first paragraph of the body text for that event or a distinct field within the event data? The former is more streamlined but less flexible...

**Comment by duhaime** [comment]
@mongmedia Should we differentiate between hovering on the card (which on click sends user to event detail page) and hovering on the Register button (which on click sends users to some event registration form)? It seems like hovering on the card should display the stripe and hovering on the button should trigger button hover state--does that sound right?

**Comment by duhaime** [comment]
@mongmedia Should the images on the left hand side resize as the viewport shrinks in width, or should they stay statically sized? The square cards on the bottom will need to shrink as the viewport loses width. If the images for upcoming events also must shrink, they may need to have less height than the text to their right...

**Comment by mongmedia** [comment]
For the buttons, there will be 2 fields to assign to this 1) destination URL and 2) the text as it should appear.  Some actions will be "Register" while other free events might be something like "Learn More" if the event information is hosted at another URL at another department w/ further details.

**Comment by mongmedia** [comment]
Hello, Doug! Here are some hover states. I think it does make sense to allow users to click to the individual event page description or on the button to register if they already know what they are looking for.
<img width="799" alt="screenshot 2017-09-01 13 56 33" src="https://user-images.githubusercontent.com/25487/29982070-4607004e-8f1e-11e7-8a85-a9dfc38f7029.png">
<img width="783" alt="screenshot 2017-09-01 14 02 59" src="https://user-images.githubusercontent.com/25487/29982074-47cfb600-8f1e-11e7-9279-c6a4046001d3.png">

**Comment by mongmedia** [comment]
Date Representation for events:
<img width="715" alt="screenshot 2017-09-01 14 10 39" src="https://user-images.githubusercontent.com/25487/29982438-ba3f48f8-8f1f-11e7-8b93-6b7a7892f682.png">
<img width="250" alt="screenshot 2017-09-01 14 10 24" src="https://user-images.githubusercontent.com/25487/29982448-be75cba4-8f1f-11e7-8572-134fa8bd5a19.png">
<img width="464" alt="screenshot 2017-09-01 14 10 19" src="https://user-images.githubusercontent.com/25487/29982452-c1e47736-8f1f-11e7-8e9b-42c1aff13339.png">
<img width="204" alt="screenshot 2017-09-01 14 10 13" src="https://user-images.githubusercontent.com/25487/29982454-c435c602-8f1f-11e7-9726-ffa3d4bddecc.png">
<img width="783" alt="screenshot 2017-09-01 14 02 59" src="https://user-images.githubusercontent.com/25487/29982457-c66f58ac-8f1f-11e7-89c6-08518f2c67cb.png">
<img width="799" alt="screenshot 2017-09-01 13 56 33" src="https://user-images.githubusercontent.com/25487/29982460-c88cd39e-8f1f-11e7-8677-d19dc97a91ed.png">

**Comment by cderose** [comment]
In response to this question you raised, Doug, "@mongmedia @cderose Should the blurb for each event card be the first paragraph of the body text for that event or a distinct field within the event data? The former is more streamlined but less flexible..." I'm good the blurb being the first paragraph of the body text.

**Comment by duhaime** [comment]
@cderose Merci! We may need to revisit this conversation as we start collecting content, as things like <h3> blocks will appear within the first n words of a post, while the content displayed in these cards should probably not begin with those header text blocks...

**Comment by duhaime** [comment]
Libcal also supports an API that permits get requests for content. Sample libcal api query:

https://api2.libcal.com/1.0/events?iid=457&cal_id=4960&key=a774181dbfbfcfcb6d282de40cfd22d4

**Comment by duhaime** [comment]
@mongmedia Can you please upload a mock for a mobile view of the events landing page?

**Comment by mongmedia** [comment]
![mobile-events](https://user-images.githubusercontent.com/25487/31558217-02af5284-b01a-11e7-9705-8768191e99c9.png)
