### ISSUE TITLE
Event Detail Page*

### ISSUE THREAD

**Issue by mongmedia** [YaleDHLab/dhlab-site#11]
![annotated - event-page](https://user-images.githubusercontent.com/25487/30076612-718fa9a6-9247-11e7-86a5-24e8d9aceb5f.png)

Key fields for the Event Page:

Category, i.e. "workshops" - this helps users sort events by event type
Tags: ... - this can help sort events by topic
Event Title
Event Details
Event image
Event Description
Button - URL to sign up or other process for registering

The Related section can have the text-based event layout that pulls in events that have similar topic tags.

Share function: OnRollover, this will show the various share options available:
<img width="302" alt="screenshot 2017-09-05 14 55 42" src="https://user-images.githubusercontent.com/25487/30077669-8f33e096-924a-11e7-9252-9662711fb9b5.png">
<img width="311" alt="screenshot 2017-09-05 14 55 45" src="https://user-images.githubusercontent.com/25487/30077670-8f36a128-924a-11e7-9016-a2ee5460789d.png">

1) Copy URL of current page
2) E-mail to an address
3) share on Facebook
4) post on Twitter
5) share w/ Google

When the user rolls over one of these options, the icon goes from #9F9F9F to #333 to show the rollover state.

<img width="300" alt="screenshot 2017-09-05 14 59 43" src="https://user-images.githubusercontent.com/25487/30078335-e1f0b3e0-924a-11e7-8fe0-d86c7bce00d9.png">

**Comment by mongmedia** [comment]
![mobile-events](https://user-images.githubusercontent.com/25487/29372497-4e8b3b06-8279-11e7-987f-af9a1c02a6de.png)

**Comment by duhaime** [comment]
@mongmedia Can you please upload a mobile view for event detail pages?

**Comment by mongmedia** [comment]
This is the event detail page.  
FYI, let's shorten "Maps & Directions" to "Directions" 

![mobile-eventdetail](https://user-images.githubusercontent.com/25487/31898264-bdb50c30-b7e6-11e7-864e-73c819b5864f.png)
