### ISSUE TITLE
Nav Dropdown order

### ISSUE THREAD

**Issue by mongmedia** [YaleDHLab/dhlab-site#114]
For the "Getting Started" sub pages, would like to list in the following order:
- Project Planning
- Corpus Creation
- Tools & Methoda
- Digital Dissemination

For "What is DH?": what are your recommendations about the order?

For "About": 
- Our Team
- Postdocs
- DH Fellows
- Executive Committee

For "Employment"
- Student Jobs
- DH Fellows
- Postdocs

For "Awards"
- Seed Grant
- Rapid Prototyping Grant
- DH Training Scholarship
- Additional Funding

**Comment by cderose** [comment]
Looks great! (small typo in "Tools and Method*s*" under "Getting Started") 

For "What is DH?", what categories are there to choose from?

**Comment by mongmedia** [comment]
The four categories are:

- Network Analysis
- Visual Analysis 
- Geospatial Analysis
- Textual Analysis

**Comment by cderose** [comment]
For that order, I lean:

Textual Analysis
Visual Analysis
Network Analysis
Geospatial Analysis

**Comment by duhaime** [comment]
@cderose @monmedia Is this all set or does it need more discussion?

**Comment by cderose** [comment]
I think we've settled on the order (TA, VA, NA, GA), but it hasn't been updated on the website dropdown itself yet.
