### ISSUE TITLE
About Landing Page*

### ISSUE THREAD

**Issue by mongmedia** [YaleDHLab/dhlab-site#12]
![annotated-about](https://user-images.githubusercontent.com/25487/30117738-21b03cb8-92ef-11e7-8471-c0fa7e6c31ee.png)

This layout has a hero image w/ the section header and page title on the lower left of the image and an image caption beneath the image area. The hero image is shorter (around 350 px for 1024 width)

The left sidebar has one submenu section followed by information about Office hours. I think of those that two HTML modules separated by a line.
The main content area will have the body text. 

This page has multiple sections. The "Our Team" section will contain staff photos with bios.
The background is a solid color with a repeating graphic along the left side of the background.
The following section is divided into 2 columns, and details the DH Lab Assistants on the left and has info about Student Jobs on the right.

**Comment by mongmedia** [comment]
![mobile-about](https://user-images.githubusercontent.com/25487/29372520-6461596a-8279-11e7-96aa-a3cc4c37bcc3.png)

**Comment by duhaime** [comment]
@mongmedia Is the header meant to be black with opacity like this? It has different styles in a number of these mocks

**Comment by duhaime** [comment]
This is done
