### ISSUE TITLE
Projects to show on Seed Grants view

### ISSUE THREAD

**Issue by mongmedia** [YaleDHLab/dhlab-site#123]
For the bottom include under the various DHLab grants, we'd like to have a selection of funded projects for visitor to referent. What are you three picks for the following?

1) Seed Grants
2) Rapid Prototyping Grants

**Comment by duhaime** [comment]
Seed Grants:

Cinecircuits: https://s3-us-west-2.amazonaws.com/cinecircuits.yale.edu/index.html
Chirila DB: http://ec2-52-55-18-79.compute-1.amazonaws.com/
La Gregueria Virtual [down at the moment]

Rapid Prototyping Grants haven't started yet

**Comment by cderose** [comment]
I second Doug's picks. If Stephen Krewson has a link and is comfortable sharing his illustration alignment tool, I'd maybe swap one of the three out to include his. 

@duhaime, have you seen La Gregueria Virtual? I'd love to see it! I didn't realize they had had a site up and running. Do you know when it will be back up?

**Comment by duhaime** [comment]
@cderose Thomas deployed it some months ago and it looked fantastic. I pinged him to see if he has an update and will update the thread once I hear back...
