### ISSUE TITLE
DH Training Scholarships page

### ISSUE THREAD

**Issue by mongmedia** [YaleDHLab/dhlab-site#124]
Would it alright if we moved the "Popular Workshops" section under the overview so that the Eligibility and Application process can exist as two columns on one row in the application section? I can also see that the bottom section underneath be a selection of upcoming events that link out to three 2018 conferences - what do you think?

**Comment by cderose** [comment]
For moving "Popular Workshops" to overview, that's good with me! For the second sentence, which three 2018 conferences do you mean?

**Comment by mongmedia** [comment]
Great question. At the bottom of the page, there is an include with placeholder called "Funded Projects" where we could add three events instead and create listings for three of the popular workshops if we already know their 2018 conference dates. (HILT, etc?) The heading might be "DH CONFERENCES" or "IN THE FIELD" or something?

**Comment by cderose** [comment]
Linking out to some of the workshops themselves sounds good. The three I'd recommend are [DHSI](http://www.dhsi.org/), [HILT](http://www.dhtraining.org/), and [DHOxSS](https://digital.humanities.ox.ac.uk/dhoxss/). We could use the heading "Popular Workshops" for them (they're not technically conferences, though there's usually a conference that syncs up with DHSI). In case any additional workshops are helpful, [here](http://web.library.yale.edu/dhlab/offcampusworkshops)'s the page from our existing site.

**Comment by mongmedia** [comment]
Thanks so much!!!
