### ISSUE TITLE
Resources Landing Page*

### ISSUE THREAD

**Issue by mongmedia** [YaleDHLab/dhlab-site#13]
![annotated-whatweoffer](https://user-images.githubusercontent.com/25487/30118257-88d02434-92f0-11e7-9d02-15086508c47a.png)

This page begins with a brief overview that sets the tone of the kind of engagement the DHLab is designed for. It then follows w/ brief blurbs that give a birdseye view about the resources visitors can find. For topics w/ more detail, users can click a button to learn more.

Because of feedback suggesting that Workshops are a sough after resource, I follow the overview w/ a display of forthcoming workshops.

*** Update *** The title for this section is now Get Started / This page is specifically the overview page about the DHLab offerings "What We Offer"

**Comment by mongmedia** [comment]
More notes on functionality:

The Consultations overview will link to a page that details DHLab consultations as well as other Digital Scholarship consultation resources.

The Space & Equipment overview will point to a page that details the available technology at the lab and eventually will be a showcase for the new lab. (It might be nice to take before/after and mid-construction shots of the space throughout the year.) 

Workshops will point to a workshops category view of the news. 

Once we know what kind of data and databases we want to point users to, we can compile this onto the Data page that will be a listing of links. 

The GitHub section will point to our the YaleDHLab GitHub page.

**Comment by duhaime** [comment]
@mongmedia Would it be possible to annotate these links within the mockups themselves? That will make it easier to parse and implement each. If we can come up with a vocabulary of identifiers for views (so that others know what mockup is intended by each route), that would be great!

**Comment by mongmedia** [comment]
![mobile-simple-resources](https://user-images.githubusercontent.com/25487/31551785-9ca06dd6-b003-11e7-8991-98631390c39e.png)

**Comment by duhaime** [comment]
This is done
