### ISSUE TITLE
Projects Issues

### ISSUE THREAD

**Issue by mongmedia** [YaleDHLab/dhlab-site#134]
- [ ] Make the "Featured" project title and hero image clickable and link to its project page
- [ ] The syntax of the categories does not include spaces - this is to facilitate how the categories are pulled in various displays. However, if would be great if the card title-boxes replace the "_" with a space in the web display.

**Comment by duhaime** [comment]
We should be able to use whitespace in project categories, and that link is added by https://github.com/YaleDHLab/dhlab-site/commit/e729ce405a671be1c79e27cc022ea95eff92ce4c which takes care of this
