### ISSUE TITLE
Methods Detail Page*

### ISSUE THREAD

**Issue by mongmedia** [YaleDHLab/dhlab-site#15]
![annotated-methods-pg](https://user-images.githubusercontent.com/25487/30133205-015e5486-9321-11e7-9a0f-15345d1b0c45.png)

The detail page for the various areas on DH will include a featured project gallery in the hero image area as well as a sidebar of exemplary projects on the left. An upcoming related event can also follow. The main content area is a text area and can include an overview followed by methods and tools. 

The other areas are featured following the description. After that, a 2-column layout can detail project planning and resources to visitors.

**Comment by duhaime** [comment]
@mongmedia The bottom of this page is close but non-identical to the bottom of https://github.com/YaleDHLab/dhlab-site/issues/17. Can we make the text portions of these elements identical, or is there an important difference between the two?

**Comment by duhaime** [comment]
@mongmedia Looking more at the guides and methods pages, should it be the case that the methods landing page and methods detail pages have identical bottom text portions, and ditto for the guides landing page and guides detail pages?

**Comment by mongmedia** [comment]
Hi, Doug - if it's best to abstract the bottom portions that way, that is no problem. My sense is that they will be repeating elements. However, as the information is more fully fleshed out by the content editors, we should make room for those to be updatable.

**Comment by mongmedia** [comment]
This mobile layout would be very similar for both methods and the project guide.

![mobile-projectguide-details](https://user-images.githubusercontent.com/25487/31553022-18a12198-b007-11e7-9965-5fc0b41013e9.png)
