### ISSUE TITLE
Methods Content

### ISSUE THREAD

**Issue by mongmedia** [YaleDHLab/dhlab-site#154]
With regards to the introduction to DH, we had a few questions:

1) What are the "flagship" projects that you'd like to list in the sidebar to each of the DH area descriptions? (visual analysis, network analysis, textual analysis, geospatial analysis) These would be recent DHLab affiliated projects that show exemplary research in these areas. We have some samples but just want to confirm w/ the team to finalize these links.

2) What are recommended applications/resources we can link to from these areas that help visitors get started in exploring these areas?

3) Should we be considering language about Digital Scholarship on campus here as well?

**Comment by duhaime** [comment]
Projects have been assigned to areas and can be reassigned, and tools/resources are outlined in methods pages, so I'm going to close this.
