### ISSUE TITLE
terms of use

### ISSUE THREAD

**Issue by mongmedia** [YaleDHLab/dhlab-site#155]
Are we ok to use this current Terms of Use document on our website?
[terms-of-use.pdf](https://github.com/YaleDHLab/dhlab-site/files/1431255/terms-of-use.pdf)

**Comment by duhaime** [comment]
I'm happy to support whatever legal suggests...

**Comment by pleonard212** [comment]
I think so; one thing I'd like to do is get the text as an actual HTML page rather than PDF...

**Comment by duhaime** [comment]
@mongmedia Would you want to mock up a simple page design for the pdf? Once we know how it should look we can build that page...
