### ISSUE TITLE
Update student jobs view to href:mailto for applications

### ISSUE THREAD

**Issue by duhaime** [YaleDHLab/dhlab-site#166]
We should make this (in Google forms?)

view: /dhlab-site/opportunities/student-jobs.html

**Comment by pleonard212** [comment]
Alternatively deep-link to different descriptions on yalestudentjobs.org...

**Comment by duhaime** [comment]
We thought we'd use a mailto because yalestudentjobs.org doesn't update query params, so we can't deeplink to DHLab jobs
