### ISSUE TITLE
Link destinations

### ISSUE THREAD

**Issue by duhaime** [YaleDHLab/dhlab-site#167]
The resource pages have a button that allows users to make an appointment--should they trigger a mailto popup, or do we want to do something more fancy?

view: /dhlab-site/resources/consultations.html

Additionally, the office hours cube on the landing page has a link to "plan your visit" -- where should this send users?

view: /dhlab-site/index.html

**Comment by pleonard212** [comment]
It's interesting to think about whether we could create 15-minute "bookings" for office hours (under the assumption that we want to keep most appointments to office hours?  Wonder how StatLab handles this? @olmjo

**Comment by olmjo** [comment]
@duhaime @pleonard212 

Our "solution" is to not have bookable sessions supported by consultants during walk-in hours. For now, appointments are only offered through myself and Joshua.

Even if a consultant says "you should come back during my next shift", there is no appointment mechanism.

**Comment by duhaime** [comment]
@olmjo Many thanks! @pleonard212 It could be interesting to pursue the idea of bookable time within the lab. It could pave the way for a system that would allow others to book time in The Cube. Maybe we can discuss more in our next production meeting?

**Comment by mongmedia** [comment]
The school of Medicine uses the RRS, Room Reservation System, which is something that ITS runs on EMS:  https://rrs.yale.edu/default.aspx

Is that something we can modify and adapt to our interface?

**Comment by duhaime** [comment]
@mongmedia That's an interesting thought. There's also the system Bass uses to loan out equipment: https://github.com/YaleSTC/reservations

This feature doesn't seem crucial to me for an initial launch, but I think it will make sense to explore options if and when we want to implement scheduling services...
