### ISSUE TITLE
Guides Detail Page*

### ISSUE THREAD

**Issue by mongmedia** [YaleDHLab/dhlab-site#17]
![annotated-start-detail](https://user-images.githubusercontent.com/25487/30134131-11970034-9324-11e7-9d0f-c7f26a4adcef.png)

These detail pages provide deep dives into the components of project planning and also includes a related event, links to resources, and readings in the left sidebar.

The content is followed by image links to the other steps as well as resources and student jobs.

**Comment by mongmedia** [comment]
This view includes a hero image, section title, image caption and description. 

Left sidebar: If there is a related event, then show just one event. If not, then show the following blocks of links (i.e. resources and readings...) If there is no event, omit both the event data as well as the horizontal rule that follows. HR elements appear only between content blocks but not before.

**Comment by mongmedia** [comment]
![mobile-projectguide-details](https://user-images.githubusercontent.com/25487/31905593-b0cb2520-b7fc-11e7-9e65-a86429fad71b.png)

**Comment by duhaime** [comment]
This is done
