### ISSUE TITLE
Hero video

### ISSUE THREAD

**Issue by duhaime** [YaleDHLab/dhlab-site#172]
We should secure the rights for an initial hero video

**Comment by mongmedia** [comment]
It's possible to purchase stock videos like this here:;

https://www.shutterstock.com/video/clip-13905131-stock-footage-plexus-fantasy-abstract-technology-and-engineering-background-with-original-organic-motion.html?src=search/tjapk7AUkbZxnRAI3pmlaw:1:31/3p

https://videohive.net/item/plexus-digital-network/13422212?ref=pro-motion&clickthrough_id=1118955751&redirect_back=true

I'll show some samples on Monday and we can vote on the one that the team likes best.

**Comment by pleonard212** [comment]
I like these quite a bit... would be also interesting to see if we could "film" a fly-through of Doug's t-SNE visualization of MK? 

I guess one problem is that it needs to loop cleanly, and not be too distracting... we could color-grade to make it darker. Anyway, something to consider for the future...
