### ISSUE TITLE
Project Landing Page*

### ISSUE THREAD

**Issue by mongmedia** [YaleDHLab/dhlab-site#18]
![annotated-projects](https://user-images.githubusercontent.com/25487/30132741-745843a4-931f-11e7-8fb9-c3e8697c4cac.png)

The Project Gallery will show a featured project, current projects as well a "From the Archives" section for projects that predate the lab.

**Comment by mongmedia** [comment]
MOBILE version
![mobile-projects](https://user-images.githubusercontent.com/25487/29369575-fb524202-8270-11e7-8b10-c1350f02a9e0.png)

The mobile view starts w/ the project hero image with a block for the category and project title. The project caption will be overlaid at the bottom of the image.

The heading Project will precede a project listing whereby the project has a thumbnail and then a text block with its category and project title. The proportions of text and image is similar to that of the mobile event listings

This is followed by the "From the Archives" heading and then a block of text-based descriptions for archived projects. These are text-based because not all archived project may have PR images

**Comment by mongmedia** [comment]
MOBILE version
![mobile-projects](https://user-images.githubusercontent.com/25487/29369575-fb524202-8270-11e7-8b10-c1350f02a9e0.png)

The mobile view starts w/ the project hero image with a block for the category and project title. The project caption will be overlaid at the bottom of the image.

The heading Project will precede a project listing whereby the project has a thumbnail and then a text block with its category and project title. The proportions of text and image is similar to that of the mobile event listings

This is followed by the "From the Archives" heading and then a block of text-based descriptions for archived projects. These are text-based because not all archived project may have PR images

**Comment by duhaime** [comment]
@mongmedia Is the hero image taller here than on the landing page? If so, how tall should this one be?

**Comment by mongmedia** [comment]
For Hero images: let's use a 16:9 aspect ratio for the Home and Project page banners. This facilitates being able to use video when available. For 1024, the height would be 576 px

**Comment by mongmedia** [comment]
<img width="300" alt="screenshot 2017-09-19 16 03 27" src="https://user-images.githubusercontent.com/25487/30615893-5c19c242-9d5e-11e7-8f22-f435026e93fb.png">

@pleonard212 , @cderose : Regarding the curation of projects, this is the list as we have it on the current website. What would you add or put into the archives (From the Archives section) and is there are particular order that you'd like to present these in?

**Comment by mongmedia** [comment]
List of archive projects at digitalhumanities.yale.edu: 

1. Ten Thousand Rooms
2. Joseph Brodsky
3. Historian's Eye
4. Cuneiform Commentaries
5. Athena
6. Babylonian Collection
7. Digitally Enabled Medieval Manuscripts
8. Works of John Edwards Online
9. Decretum Gratiani
10. Digital Himalaya
11. Modernism Lab

**Comment by mongmedia** [comment]
Another functionality for the Projects overview page would be to have a filter or sort drop over the project grid. 
<img width="981" alt="screenshot 2017-09-21 14 43 13" src="https://user-images.githubusercontent.com/25487/30712792-355452c0-9edb-11e7-9a04-9322636435b5.png">
