### ISSUE TITLE
Project Detail Page*

### ISSUE THREAD

**Issue by mongmedia** [YaleDHLab/dhlab-site#19]
![annotated project page](https://user-images.githubusercontent.com/25487/30167467-81904fd6-93b4-11e7-8914-0f0bddcb27ea.png)

The project view requires one hero image, category, title, and body description. The left sidebar content is reserved for listing the researchers/collaborators for the project.

**Comment by mongmedia** [comment]
![mobile-projectpage](https://user-images.githubusercontent.com/25487/29372461-2ebe725c-8279-11e7-8f89-dd2e9d15988a.png)

**Comment by mongmedia** [comment]
For projects from the Archive that may not have much visual documentation, this would be a good option.

![annotated-archiveproject](https://user-images.githubusercontent.com/25487/30220353-186c6038-948d-11e7-8976-e93a2c0e626c.png)

**Comment by pleonard212** [comment]
Agree! We can envision projects such as this one http://digitalhumanities.yale.edu/projects/modernism-lab finding a home there.
