### ISSUE TITLE
Project Gallery order

### ISSUE THREAD

**Issue by mongmedia** [YaleDHLab/dhlab-site#200]
Hello, @cderose and @pleonard212:  What is the order in which you'd prefer the projects to appear? 

Am in the process of adding the funded projects to the archive section as well and will have the same question on that.

We are retitling "From the Archives" as "Digital Scholarship @ Yale" too...

**Comment by cderose** [comment]
@mongmedia, if you show me the ordering logic from the backend, I'll be glad to arrange them.

**Comment by mongmedia** [comment]
@cderose :  In the yaml front matter, just add the line "order: " followed by the desired number for that page.

**Comment by cderose** [comment]
@mongmedia, great! Consider it done :)
