### ISSUE TITLE
iPad view for "Simple Pages"

### ISSUE THREAD

**Issue by mongmedia** [YaleDHLab/dhlab-site#204]
@duhaime : I revisited the simple page type which is the same layout for both Project pages that have the square image as well as the News articles and wanted to see if it's possible to adjust the iPage view (so viewports wider than mobile but smaller than the desktop) so that we can keep using the same square image rather than having to size it up to a full width image.

![ipad simple page](https://user-images.githubusercontent.com/25487/32633072-0f49daae-c574-11e7-8989-51b6105ca8b6.png)

With regards to the mobile width, I'd almost rather just redo all the square images so that they are all at 450px and can be used for the mobile view and then size down to 320 for the other layout. That way each even has only one square image rather than 2 distinct sizes. We can always adjust the mobile banner height so that the aspect ratio is closer to a square.

Take a look and let me know what we can do.

Best,
Monica

**Comment by duhaime** [comment]
@mongmedia This looks good! Feel free to implement!
