### ISSUE TITLE
Projects filter to apply to all projects

### ISSUE THREAD

**Issue by cderose** [YaleDHLab/dhlab-site#205]
The project filter by "topics" and "types" is currently for Digital Scholarship projects only. @mongmedia and I were thinking about whether we could move that filter to the top of the page and apply it to Lab projects as well as DS projects. What do you think, @duhaime?

**Comment by duhaime** [comment]
@cderose @mongmedia Sure thing. I think making that change on all filterable pages (events/news/projects) makes sense. 

Making that shift will also give us a destination to which we can send users who click on tags within an event, news, or project page. We thought those views might require a distinct page type, but I'd rather reuse our extant pages for simplicity and consistency.

**Comment by cderose** [comment]
@duhaime Wonderful! This all sounds great to me.
