### ISSUE TITLE
Footer*

### ISSUE THREAD

**Issue by mongmedia** [YaleDHLab/dhlab-site#21]
![footer](https://user-images.githubusercontent.com/25487/30116695-3e3b0910-92ec-11e7-843e-44cd82256808.png)

![footer-mobile](https://user-images.githubusercontent.com/25487/29369954-0b51424c-8272-11e7-9f6b-f8b2800d7485.png)

The footer will prominently display the official DHLab mark

**Today's Hours** will display the open hours dynamically depending on what day it is.
Our address and contact info will also be displayed

Terms of Use will follow and it will be styled the same as the headers

On Campus (or maybe Quick Links) simply surfaces links that contextualize our relationships w/ Digital Scholarship and other STEM entities on the Yale campus. Please make your suggestions about what links belong here.

**Comment by pleonard212** [comment]
Think this looks great; that dark blue really makes it stand out. I could imagine StatLab, GIS, and the broad DS site going under On Campus? (Once they're ready...)

**Comment by duhaime** [comment]
@mongmedia Can you please add the image assets for the mobile footer?

**Comment by mongmedia** [comment]
There should be a new pull request for that.

Sent from my iPhone

On Oct 20, 2017, at 1:57 PM, Douglas Duhaime <notifications@github.com<mailto:notifications@github.com>> wrote:


@mongmedia<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_mongmedia&d=DwMCaQ&c=cjytLXgP8ixuoHflwc-poQ&r=8Jph9bImGaZYoxbGc_VxQ554-KwncjdHj50LJ2PVLlY&m=GJdiiLfb7n1xxjf2AzxN3VGDO7HrunavjrAPgoV3aIQ&s=pPw3-RFCKzeE43iOIbkxtPMcLssCFB2xXz-3Ju9b6rk&e=> Can you please add the image assets for the mobile footer?
