### ISSUE TITLE
Update page headers

### ISSUE THREAD

**Issue by mongmedia** [YaleDHLab/dhlab-site#210]
♫ ♪ Everybody in the house tonight, it's an H2 party so let's have a good time! ♪ ♫
@cderose @duhaime :

FYI, for project pages with title and subheaders, please note that the title of the Page is H3 but that the section headings are H2. (And yeah, I know that's kind of backwards but oh well...)

I'll go in and change the "###" to "##" in the project pages, but just want to note this here so that we are all on the same page.

I'll also work on getting the H2 padding consistent across page layouts as well.

**Comment by duhaime** [comment]
We should reverse this for text reader parsing. Let's discuss Monday...

**Comment by duhaime** [comment]
We discussed this and decided we'd use h2 tags for the page header and h3 for the subheaders within a given post's text
