### ISSUE TITLE
Nav Menu / Search

### ISSUE THREAD

**Issue by mongmedia** [YaleDHLab/dhlab-site#22]
![nav-dropdown](https://user-images.githubusercontent.com/25487/29470837-ef08bcb8-841b-11e7-8477-040cf6425f2d.png)

![nav-light](https://user-images.githubusercontent.com/25487/29371610-c959d2aa-8276-11e7-89af-13b60c7bade4.png)

NAV LINKS: The nav will have the usual section headers. I think it would be useful to chat about whether the headers accurately reflect or open the user paths for our service model. For example, where would "What is DH?" be located as well as the Project Quick Start Guide with the various planning steps?

Social media: After a few iterations, I think that including the main social media icons by the search icon in the top right make sense. Users won't need to dig down to find them but they are sized to be visible but not distracting.

**Comment by mongmedia** [comment]
![searchview](https://user-images.githubusercontent.com/25487/29370899-c31e59e4-8274-11e7-8ecf-b9bc6891b774.png)

**Comment by mongmedia** [comment]
![nav-dropdown](https://user-images.githubusercontent.com/25487/29371901-a1a88034-8277-11e7-9875-3d37334216b3.png)

Nav colors: Default color: #9F9F9F / Active: #000000 / Rollover: #EAB755

**Comment by mongmedia** [comment]
<img width="1211" alt="screenshot 2017-08-16 12 20 29" src="https://user-images.githubusercontent.com/25487/29373812-5431efce-827d-11e7-9b4d-e1eed717cebe.png">

This is a proposal for the possible links that would go in these buckets. There are some pages that are sub-pages of others, so we can define a little hierarchy in the nav submenus where needed

**Comment by duhaime** [comment]
@mongmedia Is the header meant to be the light gray or the darker color? It appears in both colors throughout the mocks...

**Comment by mongmedia** [comment]
![searchresults](https://user-images.githubusercontent.com/25487/29428220-6a8662b8-835a-11e7-88be-0428aee009b3.png)

**Comment by mongmedia** [comment]
For search maybe we have a button that is checked to "show only events"

**Comment by mongmedia** [comment]
![resources-annotated](https://user-images.githubusercontent.com/25487/29474122-569dee32-8428-11e7-8294-bea287856880.png)

**Comment by duhaime** [comment]
@mongmedia Are there distinct views for the Opportunities header sections? I'm not sure which of the view to which these links would send users.
