### ISSUE TITLE
Newsletter email addresses

### ISSUE THREAD

**Issue by duhaime** [YaleDHLab/dhlab-site#23]
Do we have a solution for handling newsletter emails? If so, we should document the ways we'll interact with it; if not we should propose/discuss some solutions with public apis.

**Comment by mongmedia** [comment]
Currently, we use Messages, which is administered by Yale's communication area. Cathy says that there is a way to create a new template in Messages, so we would have an opportunity to update the look to match the site. 

To sign up for the newsletter, there's this page: https://messages.yale.edu/Subscribe?ReturnUrl=%2fSubscribe%2fList%2fLIB

For now, we can create a link to that page...but if it is possible to sign up on our page and magically move that data there, then I'd like to explore that.

**Comment by duhaime** [comment]
That sounds good. For the nonce we can link out, and if we learn more about any kind of interactions they make possible we can pursue those.
