### ISSUE TITLE
Calendar integrations

### ISSUE THREAD

**Issue by duhaime** [YaleDHLab/dhlab-site#24]
We should outline all of the ways in which we wish to use calendar data from our lab and those of other Yale groups.

**Comment by mongmedia** [comment]
I think at some point Themba will convene a meeting w/ the other DS folks about how to share events. Since we all plan to use Jekyll, hopefully it will make this easier to integrate. I can annotate the events view.

With regards to Yale calendars, I think this depends on where we can to post or port in data. 
There is the University Calendar at calendar.yale.edu
To submit events, one has to fill out a form for each event on the "submit an event" page.
There is only an option do "download" events as iCal data. 
I believe James Tucciarone III administers the site so he would be the ITS contact who could let us know if there might be an API.

**Comment by duhaime** [comment]
Sounds good, I'll write James...

**Comment by mongmedia** [comment]
![events-list-annotated](https://user-images.githubusercontent.com/25487/29476220-e452234e-8430-11e7-9c36-25faa778ac9d.png)

For our Events page, we can start w/ just integrating text-only data on events around Digital Scholarships that are not hosted by DHLab. We we will need to chat w/ Josh and Jonathan about how to pull in their info and also the fields we need for each event. 

All the other feeds on our page are DHLab events - the main content is Upcoming Events, the bottom row is just 3 past events.

**Comment by mongmedia** [comment]
But yes, I think we should audit all the calendars at Yale to see which ones we should make sure to push our events to. Let's also check in w/ Cathy about who she publicizes to.

**Comment by duhaime** [comment]
ping @cderose

**Comment by duhaime** [comment]
Update from James:

Thanks for reaching out about the University Bedework calendar system!  We’ve recently launched a major upgrade and this is a great time to get involved with the calendar.
 
The system can certainly provide a data feed that can be imported by third-party systems (indeed, we already have integrations with systems such as YaleSites/Drupal and the Yale Arts calendar).  The system can provide the data feed in a number of formats – note, however, the JSON feed format is centrally supported.
 
Currently, we are unable to import events into Bedework from third-party system, however we are developing this feature and anticipate it will be available around the end of the calendar year.  We’re happy to provide additional information about this approach as it becomes available.  In the meantime, if you believe you will be posting a number of events, we can also discuss adding your group to the calendar.

**Comment by duhaime** [comment]
Further update from James:

-          Base URL:
o    http://calendar.yale.edu/feeder/main/eventsFeed.do?f=y&sort=dtstart.utc:asc
o    (parameters may be added as &paramName=value)
 
-          Tags:
o    Tags may be added to filter the result set in the format &fexpr=(vpath=”vPathDirectory”).
o    Please let me know which, if any, vpaths your application will require and I can collate a list.
 
-          Start Date/End Date:
o    The result set may also be restricted by date in the formats &start=YYYYMMDD and &end=YYYYMMDD .
o    Note one month is the maximum range allowed.
o    Also note if &start=YYYYMMDD is used, then &end=YYYYMMDD must also be included.
 
-          Feed Format:
o    You must provide a feed format (i.e., JSON) in the fomats &skinName=format or &format=format (depending on the required format)
o    JSON is the centrally supported feed format (&skinName=list-json).
 
-          Count:
o    Requests must include the &count=number parameter.
o    Note the maximum count is 240 (&count=240)
 
-          General:
o    Without a date parameter, the feed currently returns the next 180 days (we are working with our vendor to increase this to 365).

sample endpoint: http://calendar.yale.edu/feeder/main/eventsFeed.do?f=y&sort=dtstart.utc:asc&skinName=list-json&count=240

**Comment by duhaime** [comment]
For the record, Yale has two calendaring systems: 1) Schedule.yale.edu / libCAL, 2) Bedeworks. The former is able to schedule and reserve rooms; we should verify if the latter is capable of the same...

**Comment by duhaime** [comment]
We won't need this
