### ISSUE TITLE
Third Party Integrations

### ISSUE THREAD

**Issue by mongmedia** [YaleDHLab/dhlab-site#25]
This is just a list of third party interactions that our site will have. Please add your suggestions.

- Grant Applications: We can look at doing a Google Form that feeds to a spreadsheet?
- Post Doc or Fellowships Applications: Same here
- Event registration: This will continue to link to the Library's event registration page
- Student Jobs - Apply: Is there already a site that manages this at Yale? 
- YaleDHLab Github 
- Social media: Is it possible to auto-publish an event to social media when creating the event in Jekyll?
- Calendars: Per the last issue, we need to figure out where we want to push event to and where we want to import events from.
- Yale Library Applications: Are there any elements from the Yale Library site that would be useful to integrate? I'm thinking about the Data Resources page in specific.

**Comment by duhaime** [comment]
@mongmedia I think we should break each of these out into discrete issues once the list is complete, as each of these will require a good deal of special care

**Comment by duhaime** [comment]
What are the integrations with GitHub?

**Comment by mongmedia** [comment]
On the resources page, I think we just link out to the YaleDHLab Github page.

**Comment by duhaime** [comment]
Ah yes, but that's just a link, not an integration right?

**Comment by mongmedia** [comment]
Right. Would you imagine potentially anything more involved in terms of sharing code or encourage users to sign up and join us on GitHub? Just leaving that open if you think it would be useful.

**Comment by duhaime** [comment]
I think a link will be just fine.

**Comment by duhaime** [comment]
@mongmedia I'm closing this one so we can partition individual elements into discrete issues.
