### ISSUE TITLE
Event registrations

### ISSUE THREAD

**Issue by duhaime** [YaleDHLab/dhlab-site#26]
We should discuss how we want to handle event registrations

**Comment by mongmedia** [comment]
I believe that DHLab events are registered using Yale Library's event registration page. @cderose — do you think the "register" link just jumps to that page? What is the URL for that? Or does each event generate a unique event registration page?

**Comment by cderose** [comment]
Would it be possible to keep it so that I link to a URL on an event by event basis? Currently, events are posted to the [YUL Instruction Calendar](http://schedule.yale.edu/calendar/instruction/?cid=4960&t=d&d=0000-00-00&cal%5B%5D=4960), and each individual event on that calendar has its own URL.

**Comment by olmjo** [comment]
Take a look. Proposed fix:

- uses an event-by-event registration url for the button's target
- does not create a registration button if no url is provided
