### ISSUE TITLE
404 Page

### ISSUE THREAD

**Issue by mongmedia** [YaleDHLab/dhlab-site#263]
What did we settle on for the 404 page?

**Comment by duhaime** [comment]
I don't think we have a solid plan. I hope to have a chance to try a sketch or two before the end of the week...

**Comment by mongmedia** [comment]
Hi, Doug - I will e-mail you the SVG file as github doesn't support that transmission here. The background color can be #3BA2DB. Maybe some random punch holes flash white and yellow?

Thanks!
Monica

**Comment by duhaime** [comment]
Here's where I landed: https://yaledhlab.github.io/dhlab-site/cats-on-wheels.html
