### ISSUE TITLE
Handling grant/postdoc applications

### ISSUE THREAD

**Issue by duhaime** [YaleDHLab/dhlab-site#27]
We should outline the ways we want to handle grant applications. Google Forms is my preferred solution, as they have flexible apis to route uploaded data (including multipart uploads) to custom targets.

**Comment by mongmedia** [comment]
I will work on prototyping a sample application form in Google Forms that directs data into a shared DHLab spreadsheet.

**Comment by duhaime** [comment]
@mongmedia That sounds good. If you want, we can use google script to give us complete flexibility over the form design--we should talk through these ideas tomorrow...

**Comment by duhaime** [comment]
This is done
