### ISSUE TITLE
On Campus events

### ISSUE THREAD

**Issue by mongmedia** [YaleDHLab/dhlab-site#274]
Events page: Let's figure out what to curate for "On Campus" events for the launch.

**Comment by duhaime** [comment]
I think we should gather from the YCRC, YINS, and StatLab calendars

**Comment by cderose** [comment]
I second @duhaime's picks.

**Comment by duhaime** [comment]
@cderose @mongmedia The big question on this front is whether we plan to manually curate on campus events, or whether we want to automate the process. If nobody feels strongly either way, I'd vote for manual curation, as that will prioritize data precision over recall and will keep things looking good.

**Comment by cderose** [comment]
@duhaime @mongmedia Manual curation sounds good to me!
