### ISSUE TITLE
Event dates for previous workshops

### ISSUE THREAD

**Issue by duhaime** [YaleDHLab/dhlab-site#292]
Should we backfill these? The workshops route (/dhlab-site/resources/workshops.html) only has dates for some workshops, so they look a little uneven:

![screen shot 2017-12-04 at 3 49 50 pm](https://user-images.githubusercontent.com/4801116/33575507-e12ffa5e-d90a-11e7-8148-1cdecb11cd0b.png)

**Comment by mongmedia** [comment]
Yes, will work on that today.
