### ISSUE TITLE
Idea for Digital Scholarship projects (bottom of Projects Page)

### ISSUE THREAD

**Issue by pleonard212** [YaleDHLab/dhlab-site#297]
We could design a small ribbon (like a diagonal band) that goes across the corner of each project that we've funded/supported. So for example it would go on Cinecircuits but not 10,000 Rooms.  This would just be for the small icons at the bottom, under Digital Scholarship projects...

**Comment by mongmedia** [comment]
Let's try adding this badge to the projects marked as "funded":

<img width="194" alt="screenshot 2017-12-06 14 24 25" src="https://user-images.githubusercontent.com/25487/33680964-374f15f0-da91-11e7-92bd-48f02573a6ac.png">

Will add the badge to the asset branding folder

**Comment by mongmedia** [comment]
The link to the badge is here: https://github.com/YaleDHLab/dhlab-site/blob/master/assets/images/branding/dhlab-badge.svg
