### ISSUE TITLE
News/Events/Simple Page hero image and metadata

### ISSUE THREAD

**Issue by mongmedia** [YaleDHLab/dhlab-site#299]
Hi, Doug:

I had one last thought regarding the "hero" area for the events/news detail pages. Currently the hero takes up 100% width and the date/time/location info drops out of view.

In order to keep our workflow as simple as possible, I think we should just treat this hero area similarly to the way images/title/metadata are styled in the 'horizontal-card' style for the screen widths between 400 and 700px. 

That way, the images can always be at 400 px without issue. Also, we'll be able to preserve the info for the events which will be important to mobile users on the go.

Let me know if you need more detailed explanation.

Thanks,
Monica

**Comment by duhaime** [comment]
This is done
