### ISSUE TITLE
Containers are irregularly sized

### ISSUE THREAD

**Issue by duhaime** [YaleDHLab/dhlab-site#30]
We should come up with a vocabulary of central page container sizes (large, medium, etc.) so that we can apply consistent styles for center container widths

**Comment by mongmedia** [comment]
The large home page layout has a grid w/ 400px width for each column and 24 px of padding in between. 

![home-page grid](https://user-images.githubusercontent.com/25487/29841098-28998732-8cd2-11e7-82e1-8585d4ff7bce.png)

The white space outside the grid is about 60 px (5% of the screen width) on each side.

**Comment by duhaime** [comment]
We've now moved to a consistent container size, so I'll close this one...
