### ISSUE TITLE
High-res about photos

### ISSUE THREAD

**Issue by duhaime** [YaleDHLab/dhlab-site#305]
@mongmedia Would you be able to export about page images for each headshot? They should be 1300x1300 at jpg quality ~80%, as they are displayed at 650x650 once the browser window is 700px wide or less.

**Comment by mongmedia** [comment]
have updates for the DHLab team and also the postdocs. Will see about the DH fellows - I will need to check w/ Cathy about the resolution of the image that they had submitted.

**Comment by duhaime** [comment]
This is done!
