### ISSUE TITLE
Consider hero movie compression

### ISSUE THREAD

**Issue by pleonard212** [YaleDHLab/dhlab-site#311]
It looks like we might be able to squish the size of hero.mp4 from 20megs down to 7.6 megs if we run it thru Handbrake.  At least, I can't tell the difference in quality (still 30fps, original res, etc.) Maybe worth some tests?  Not sure about .ogg optimization, but probably there's some ffmpeg command to do that...

**Comment by duhaime** [comment]
That worked out nicely! The new mp4 is now loaded!

**Comment by duhaime** [comment]
Curiously many of the handbrake default setting groups are clipping the last bit of the video, which breaks the loop sequence...

**Comment by duhaime** [comment]
This setting group produced nicely minified results:

![screen shot 2018-01-30 at 2 24 39 pm](https://user-images.githubusercontent.com/4801116/35587082-b6ca37c4-05ca-11e8-934f-b40927a8aa6c.png)
