### ISSUE TITLE
Event Teasers

### ISSUE THREAD

**Issue by mongmedia** [YaleDHLab/dhlab-site#313]
@cderose - I had a question about the teaser text for forthcoming events and news. Right now they are listed showing the first set number of characters of the teaser text, which was auto-generated. Seeing that the amount of space allowed for text can accommodate more content, do you think it makes sense to maybe show the teaser text at the end of full sentences, rather than in the middle of a sentence with "..." at the end? 

https://yaledhlab.github.io/dhlab-site/news.html

**Comment by cderose** [comment]
@mongmedia That sounds good! We could also increase the set number of characters to whatever looks good aesthetically. The ellipses are a nice indicator that there's more content if users click. Either way!
