### ISSUE TITLE
Style Guide

### ISSUE THREAD

**Issue by mongmedia** [YaleDHLab/dhlab-site#32]
Updating the Style Guide based on the 1024 px wide layout.

![screen shot 2017-08-30 at 2 28 26 pm](https://user-images.githubusercontent.com/25487/29888607-883e423c-8d8f-11e7-9983-3564cc7ea6ae.png)

**Navigation Menu**
Background bar:  100% width, 50 px height, #000 at 30% transparency
Nav Link — Default: #9F9F9F / Interstate Bold / 14 px 
Nav Link — Active: #FFFFFF / Interstate Bold / 14 px
Nav Link — OnRollover: #EAB755 / Interstate Bold / 14 px
Social Media icons: 16px height, position vertical-middle
DHLab Logo: (See assets folder: DHLab-logo.png): 150 x 64 px
Drop down background: 200 px / #000 / 70% transparency

**Hero image**
100% width / 400 px height
"Yale Digital Scholarship" header: 24 px / YaleDesign small caps / #fff
"Yale Digital Humanities Lab" header: 60 px / YaleNew Roman / #fff

**Button Styling**
Dimensions: 36 px height / text width plus 20px padding width on each side
OffState — Border color: #EAB755 / Text color: #fff
OnRollover — Background color: #EAB755 / Tex color: #000

![screen shot 2017-08-30 at 3 06 29 pm](https://user-images.githubusercontent.com/25487/29890218-dc0f1e4a-8d94-11e7-8e03-bf68906a93a2.png)

**Events Feed**
Home Page Category: Interstate bold / 14 px / uppercase / #333
Image size: 250 x 250 px / Padding between events: 76 px
Date: Square background: 50x50 px / month: Interstate bold, 16 px, uppercase / date: interstate bold, 26 px, line-spacing 24 / 15px padding-left and padding-top
Event Tag: Interstate Regular / 12 px / uppercase / #333
Event Title Heading: Interstate Bold / 18 px / linespacing: 21 / #333
Event Title Background: 220 px width / 110 px height / border: #95989A at 50% / Background blur to create frosted glass effect. Float 50% of the bg height over the image.

**What's New**
Image: 900 px x 500 px
Same treatment for Event Title w/ Tag.
Call to action:  Text with button for E-News sign up. Take users to https://messages.yale.edu/Subscribe/
Call text:  interstate regular / 14 px / #333

**Spotlight**
Image: 576 x 400 px
Headling similar to event titles.
Call to action: Jump to project guide

**Footer**
Yale DHLab official mark / then two columns of info and links
Column header: Interstate bold / 15 px / uppercase (Today's Hour & On Campus)
Link/ info text: interstate regular / 15 px / #fff
Background color: #051D38

![container-1024px](https://user-images.githubusercontent.com/25487/29892270-06472700-8d9c-11e7-8261-1ccf53426797.png)

**Comment by mongmedia** [comment]
Update to Events Listing for 1024px container

![container-1024px events](https://user-images.githubusercontent.com/25487/29894070-2c2005cc-8da2-11e7-89ea-697883426052.png)

**Comment by mongmedia** [comment]
![container-1024px events-description](https://user-images.githubusercontent.com/25487/29938549-15b5a8b8-8e57-11e7-9a5f-b6e4ad0634dd.png)

**Comment by mongmedia** [comment]
![container-1024px what is](https://user-images.githubusercontent.com/25487/29944358-42691534-8e6b-11e7-9335-1831f8cecc18.png)

This page will show how many simple pages will be formatted.

**Global Styles**

Body Text: The reading body text should be set to 15 px, interstate light, #333 / line-spacing 24
Paragraph headings: Interstate Bold, 15 px / #333

Individual Pages will have similar approaches to titling:

Headline or Page Title: 21 px / Interstate Bold / line-spacing 25
Subheading (usually appearing over the title that indicates a category or section)

**Comment by duhaime** [comment]
Noop and dated so closing
