### ISSUE TITLE
Generate related news and events data model

### ISSUE THREAD

**Issue by mongmedia** [YaleDHLab/dhlab-site#329]
@cderose  @pleonard212  @duhaime  What is the best way to cull related content for News posts or archive posts?
Do you want to organize by proximity to dates or by shared categories or tags?

Sample pages:

http://127.0.0.1:4000/dhlab-site/news/2018-01-11-webgl-meetup.html

http://127.0.0.1:4000/dhlab-site/projects/gregueria.html

**Comment by duhaime** [comment]
The fastest way will be a set intersection on tags and categories, but we can get elaborate if that's desired.

Even a simple vector space model would capture tons of signal without word embeddings or anything fancy, though we'd have to continually regenerate data structures when adding or editing new records. We've avoided this to date because there hasn't seemed to be much return on investment, but we can implement something before launching...

**Comment by cderose** [comment]
Categories sounds good to me!

**Comment by mongmedia** [comment]
Hi, @duhaime:

In archive.html, I updated line 9 to:
 {% if item.title != page.title and item.categories == page.categories %}

What I'm finding, however, is that it only shows related posts for items that have matches of all categories. Rather, I think we'd be able to display more items if the had one matching category rather than all. Can you take a look at this?

**Comment by duhaime** [comment]
Hopefully the solution we just talked through will work out nicely (once Jekyll gets around to processing all 1.3M files in our site...)

**Comment by mongmedia** [comment]
@duhaime: With regards to how related content is selected for a given project or event page, I think the point system that you recommended does sound good.  @cderose suggests that if we show related projects on our methods pages such as Textual Analysis (http://127.0.0.1:4000/dhlab-site/methods/textual_analysis.html) it would also be ideal to push the DHLab current projects to the top of the "Selected Projects" List.

Here are the views where we'd like to make sure the related Categories works:

Archive project view:
http://127.0.0.1:4000/dhlab-site/projects/himalaya.html

Methods pages in Selected Projects sidebar:
http://127.0.0.1:4000/dhlab-site/methods/visual_analysis.html

News event: To not repeat the event of the current page and then show related events
http://127.0.0.1:4000/dhlab-site/events/2018-04-06-beyond-boundaries.html
