### ISSUE TITLE
Project Filtering

### ISSUE THREAD

**Issue by mongmedia** [YaleDHLab/dhlab-site#335]
@duhaime : Cathy had asked about whether or not it is possible to add project filtering to the main featured projects as well. I think it would entail adding a similar header as the one over the archive grid "Digital Scholarship @ Yale" with the HR below. I think we'd just call it "Featured Projects"
Let me know what you think as far as how the back end would handle this.

Best,
Monica

**Comment by duhaime** [comment]
dupe of #205
