### ISSUE TITLE
Event Titling

### ISSUE THREAD

**Issue by mongmedia** [YaleDHLab/dhlab-site#355]
Create a way to show a short hand version of the titles of events for the home page, yet keep the full name for the individual event page.

**Comment by duhaime** [comment]
@mongmedia Can you please provide a list of events for which we want shortened titles?

**Comment by mongmedia** [comment]
@duhaime : This is an example of an event w/ a long title: http://127.0.0.1:4000/dhlab-site/events/2018-02-07-Murray.html

Is it possible to create a "short title" field in the front matter so that if we do populate that for an event, then the home page grabs the shorter title for display? What Cathy and I are finding is that many people name talks arounds their project or paper titles, which are much lengthier than what space allows for even headlines.

For the Douglass event, the short title would be "Mapping Frederick Douglass"

**Comment by duhaime** [comment]
@mongmedia Sure it's possible. We just need the full set of titles to adjust to know which ones need the special key. Are there others to shorten, or just that one?

**Comment by mongmedia** [comment]
So far it's just that one but I imagine this may come up again for future talks.

**Comment by mongmedia** [comment]
All set!

**Comment by duhaime** [comment]
@mongmedia Nicely done!
