### ISSUE TITLE
Managing Tags

### ISSUE THREAD

**Issue by duhaime** [YaleDHLab/dhlab-site#36]
We should discuss how we wish to use tags to control content positioning in the site. The pages that seem to require some usage of tags include:

Guides detail page: The content in the left-sidebar should be determined by tag similarity
Event detail page: The related events content should be determined by tag similarity
Methods detail page: The content in the left-sidebar should be determined by tag similarity
News detail page: The related content at the bottom should be determined by tag similarity

**Comment by mongmedia** [comment]
I think that Projects can also be tagged by the DH bucket that they belong to so that they can be filtered in the Project Gallery too.
