### ISSUE TITLE
Hours feed

### ISSUE THREAD

**Issue by mongmedia** [YaleDHLab/dhlab-site#362]
@duhaime - after reviewing the Today's Hours w/ @cderose , we are wondering if there is a more direct way for the Today's Hours content to feed in from the central library site? That way, there is only one place to log exceptions and holidays. Let us know.

**Comment by duhaime** [comment]
Url endpoint: https://api3.libcal.com/api_hours_grid.php?format=jsonld&iid=457&lid=4261
