### ISSUE TITLE
About Detail Page*

### ISSUE THREAD

**Issue by mongmedia** [YaleDHLab/dhlab-site#37]
This is a layout that can be used for listing the Postdoctoral Associates as well as DH Teaching Fellows. It starts w/ a description about the position followed by a listing of member for the current year and then ends w/ a section that lists past participants and another column of related content.

![annotated postdocs](https://user-images.githubusercontent.com/25487/30118030-f36e533e-92ef-11e7-8223-6a5cd9bbc485.png)

**Comment by cderose** [comment]
Just leaving a note here for myself to add a soft return between postdoc name and departmental affiliation

**Comment by duhaime** [comment]
This is done
