### ISSUE TITLE
News Render

### ISSUE THREAD

**Issue by mongmedia** [YaleDHLab/dhlab-site#376]
Hi, @duhaime and @cderose :  So I was able to get posts to hide by adding "render: false" to posts and then updating a few includes around the site. The only one I couldn't not figure out was for the Home page. We have the "What's New" card showing the news draft about the Franke Room. It has the "render: false" front matter attached to it. I tried the various code snippets that I had on hand but it didn't seem to work here.

Can you give me some more clues on how to do this on Monday? Otherwise I was able to hide events on the home page as well as draft items on the landing pages for News and Events.

**Comment by duhaime** [comment]
It looks like [this](https://github.com/YaleDHLab/dhlab-site/blob/master/_includes/news/get_featured_news.html) is the template responsible for the featured news item--we should conditionalize the rendering in that partial...

**Comment by mongmedia** [comment]
Thank you for the jekyll jedi lesson! All set!
