### ISSUE TITLE
Desktop Navigation Menu*

### ISSUE THREAD

**Issue by mongmedia** [YaleDHLab/dhlab-site#38]
![annotated-nav-about](https://user-images.githubusercontent.com/25487/30131387-94e4fbb2-931a-11e7-9d90-6848132c8c0e.png)

![annotated-nav-opps](https://user-images.githubusercontent.com/25487/30131391-97c77a26-931a-11e7-9a7c-b4ee26bc65dd.png)

![annotated-nav-news-events](https://user-images.githubusercontent.com/25487/30131396-9bfa148c-931a-11e7-82a7-9d2ac198550c.png)

![annotated-nav-get-started](https://user-images.githubusercontent.com/25487/30131543-2dc14430-931b-11e7-962f-33105608eb8c.png)

Because the sub links have been moved out of the Project dropdown, I think Projects in the header should just link directly to its project gallery page.

**Comment by duhaime** [comment]
This is done
