### ISSUE TITLE
URL Styling

### ISSUE THREAD

**Issue by mongmedia** [YaleDHLab/dhlab-site#383]
@duhaime : Create a way to style a short URL for a news or event item, i.e. 

short_URL: _______

**Comment by duhaime** [comment]
We can achieve this by adding `permalink: '/beyond-boundaries/'` (e.g.) to the frontmatter of a post. This would make DOMAIN/dhlab-site/beyond-boundaries resolve to the given page.

Does this sound good @cderose @mongmedia ?

**Comment by mongmedia** [comment]
Sounds great!
Monica


On Feb 7, 2018, at 12:08 PM, Douglas Duhaime <notifications@github.com<mailto:notifications@github.com>> wrote:


We can achieve this by adding permalink: '/beyond-boundaries/' (e.g.) to the frontmatter of a post. This would make DOMAIN/dhlab-site/beyond-boundaries resolve to the given page.

Does this sound good @cderose<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_cderose&d=DwMFaQ&c=cjytLXgP8ixuoHflwc-poQ&r=8Jph9bImGaZYoxbGc_VxQ554-KwncjdHj50LJ2PVLlY&m=WLMtFQqathHfa7H-4-KGOFUahEYCtJEKTLJok1aY6SM&s=DM0d2-jmi-dNi6lE6hUGdTf2VfQjlSRwMAM9zqzgMzI&e=> @mongmedia<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_mongmedia&d=DwMFaQ&c=cjytLXgP8ixuoHflwc-poQ&r=8Jph9bImGaZYoxbGc_VxQ554-KwncjdHj50LJ2PVLlY&m=WLMtFQqathHfa7H-4-KGOFUahEYCtJEKTLJok1aY6SM&s=SKKljREfKcS-uD4Yxk3QA7P7GgyIjDm0mn8cqpI1rkQ&e=> ?

**Comment by duhaime** [comment]
Here's the reference in case that helps: https://jekyllrb.com/docs/permalinks/

**Comment by mongmedia** [comment]
If I use '/beyond-boundaires/' for this year's event and then also add it to the one for next year, will I need to remember to remove it from the 2018 post?

**Comment by duhaime** [comment]
This is settled, so closing
