### ISSUE TITLE
News Landing Page*

### ISSUE THREAD

**Issue by mongmedia** [YaleDHLab/dhlab-site#39]
![annotate-newslanding](https://user-images.githubusercontent.com/25487/30176538-caf1e3b2-93d0-11e7-917e-0a7614bf278b.png)

**Comment by mongmedia** [comment]
@cderose: Here is the current concept for the News Landing Page. I thought we could also take a stab at listing the News categories as well:

- Announcements
- Funding
- Student Jobs
- In the Field
- ....what else?

**Comment by duhaime** [comment]
@mongmedia What do you imagine happening when users click "Submit News?"

**Comment by duhaime** [comment]
@mongmedia Can you please upload a mobile view for the news landing page?

**Comment by mongmedia** [comment]
![news view by filter-category](https://user-images.githubusercontent.com/25487/31553585-f2a4fb5c-b008-11e7-91e0-1d1bd9c864fa.png)

**Comment by mongmedia** [comment]
![mobile-news-story](https://user-images.githubusercontent.com/25487/31554184-d0645a18-b00a-11e7-8540-e81620d5f3c7.png)
![mobile-news](https://user-images.githubusercontent.com/25487/31554186-d096a07c-b00a-11e7-8dde-d2df3b9d3b57.png)

**Comment by duhaime** [comment]
@mongmedia Could you please update the mock for the mobile view? This data isn't available on news cards.

**Comment by mongmedia** [comment]
All set!

**Comment by mongmedia** [comment]
FYI, the Submit Your News goes to the Google Form:

https://docs.google.com/forms/d/1HvwWecpYODW3DoMVTnJy7beOMfechLPIiVhV5ekvYNI/prefill
