### ISSUE TITLE
Safari Issues

### ISSUE THREAD

**Issue by mongmedia** [YaleDHLab/dhlab-site#390]
- [ ] Project images on projects landing page are not displaying on Safari 9.1 on OS 10.11.4
![screen shot 2018-02-07 at 12 51 49 pm](https://user-images.githubusercontent.com/25487/35932515-d10ede5a-0c05-11e8-86ef-7096a5f64b60.png)

**Comment by duhaime** [comment]
@mongmedia Rather than a checklist, can we make one issue per problem? That makes it easier to show which code resolves which issues

**Comment by duhaime** [comment]
Can you also please document the browser and OS versions?

**Comment by mongmedia** [comment]
The comment is revised to reflect the info

**Comment by duhaime** [comment]
Excellent, thank you!

We should discuss whether we want to support Safari 9 -- it's two major releases out of date and has small usage stats: http://gs.statcounter.com/browser-version-partially-combined-market-share/desktop/worldwide/#monthly-201701-201801

<img width="675" alt="screen shot 2018-02-07 at 1 26 36 pm" src="https://user-images.githubusercontent.com/4801116/35934111-8f9f215a-0c0a-11e8-9da8-e35a17f76e9d.png">

**Comment by mongmedia** [comment]
Hi, Doug:

I think it’s sufficient to support the more current versions of these browsers.

I’m due for a system update!
Monica



On Feb 7, 2018, at 1:27 PM, Douglas Duhaime <notifications@github.com<mailto:notifications@github.com>> wrote:


Excellent, thank you!

We should discuss whether we want to support Safari 9 -- it's two major releases out of date and has small usage stats: http://gs.statcounter.com/browser-version-partially-combined-market-share/desktop/worldwide/#monthly-201701-201801<https://urldefense.proofpoint.com/v2/url?u=http-3A__gs.statcounter.com_browser-2Dversion-2Dpartially-2Dcombined-2Dmarket-2Dshare_desktop_worldwide_-23monthly-2D201701-2D201801&d=DwMFaQ&c=cjytLXgP8ixuoHflwc-poQ&r=8Jph9bImGaZYoxbGc_VxQ554-KwncjdHj50LJ2PVLlY&m=ykV8UyDfO8jXvDLaJB3xblaeyr4lJPmL2wBnoj6xhmo&s=2e2YvUikrOgrsOFOTsMy9RRmhCEitWASq2YD-5Pi3ik&e=>

[screen shot 2018-02-07 at 1 26 36 pm]<https://urldefense.proofpoint.com/v2/url?u=https-3A__user-2Dimages.githubusercontent.com_4801116_35934111-2D8f9f215a-2D0c0a-2D11e8-2D9da8-2De35a17f76e9d.png&d=DwMFaQ&c=cjytLXgP8ixuoHflwc-poQ&r=8Jph9bImGaZYoxbGc_VxQ554-KwncjdHj50LJ2PVLlY&m=ykV8UyDfO8jXvDLaJB3xblaeyr4lJPmL2wBnoj6xhmo&s=qCPCi0pZPuFl8TxblYGPJK1oIL6b3leMoBCKifnJpds&e=>

**Comment by duhaime** [comment]
@mongmedia Okay that sounds good

**Comment by duhaime** [comment]
I'll close this for now, but we can open new issues with any cross-browser discoveries!
