### ISSUE TITLE
Request DNS binding

### ISSUE THREAD

**Issue by duhaime** [YaleDHLab/dhlab-site#391]
via service now

**Comment by mongmedia** [comment]
Hi, Doug! I place an "order" in the Service Now system.
Request number: REQ0225032

Also, @duhaime and @pleonard212 - I just want to confirm the URLs we are redirecting. Do you want both http://dhlab.yale.edu AND http://digitalhumanities.yale.edu/ to point to the new site? Or just http://dhlab.yale.edu?

**Comment by pleonard212** [comment]
I think both, and I can create a set of mappings that will accommodate
digital humanities.yale.edu 's urls for redirecting...
