### ISSUE TITLE
Firefox Issues

### ISSUE THREAD

**Issue by mongmedia** [YaleDHLab/dhlab-site#394]
- [ ] Projects landing page: The Archive grid shows up as only 4 columns instead of 5
- [ ] Events page: same issue with past events grid

**Comment by duhaime** [comment]
@mongmedia Can you please note the browser and OS versions?

**Comment by mongmedia** [comment]
Sorry! It's Firefox 58.0.2 in the OS El Capitan 10.11.6

**Comment by duhaime** [comment]
Haha, no worries! We just need to make sure to track the versions with the browser testing!
