### ISSUE TITLE
Internet Explorer Issues

### ISSUE THREAD

**Issue by mongmedia** [YaleDHLab/dhlab-site#399]
IE version 11.0.96 / Windows (DHLab station) 
- [x] NEWS: News posts do not appear after featured news
- [x] EVENTS: Past event grid does not appear near bottom
- [x] PROJECTS: Neither the main projects nor the archived project appear
   -- Console message:  Script438: Object doesn't support property or method 'includes'
   -- {n.className=n.className**.includes**(" active ")?n.className.replace(" active ",""):n.className+" active "}
   -- File bundle.js, line: 1, col: 410747
- [x] Parallax function is not working for the banner images
- [x] What is DH? (Methods): The onRollover for the grid images makes the image almost disappear except for the text
- [ ] Methods pages: The onRollover for the methods images makes them disappear
- [x] DHLab logo: disappears after rotation

**Comment by duhaime** [comment]
The transform style property is not supported by any IE: https://developer.mozilla.org/en-US/docs/Web/CSS/transform-style#Browser_compatibility
