### ISSUE TITLE
Microsoft Edge issues

### ISSUE THREAD

**Issue by mongmedia** [YaleDHLab/dhlab-site#400]
- [ ] PROJECTS: The archive grid shows just 4 of the 5 columns
- [ ] EVENTS: The past events archive grid shows 4 of 5 columns

**Comment by duhaime** [comment]
Browser and OS versions?

**Comment by mongmedia** [comment]
Microsoft Edge: 41.16299.15.0
Microsoft Edge HTML: 16.16299
This is on the lab Thinkpad: Windows 10 pro / Version 1709 / OS Build 16299.192
