### ISSUE TITLE
URL Update

### ISSUE THREAD

**Issue by mongmedia** [YaleDHLab/dhlab-site#402]
Have the URL's resolve for addresses that don't include the .html extension

<img width="818" alt="screenshot 2018-02-15 10 35 18" src="https://user-images.githubusercontent.com/25487/36264932-0966b368-123c-11e8-8365-fff4a9d35521.png">

**Comment by duhaime** [comment]
@mongmedia I don't think we should support this kind of linking. It would be a great deal of work and would mean rewriting lots of internal links--I think we should file this under "will not do"

**Comment by duhaime** [comment]
@mongmedia We can handle this via the solution to #405. It would take a little bit of doing to glob over all site files and create representations of them without .html extensions, but we could do this programmatically and redirect to the .html extensions as the canonical urls...
