### ISSUE TITLE
Awards Landing Page*

### ISSUE THREAD

**Issue by duhaime** [YaleDHLab/dhlab-site#41]

**Comment by mongmedia** [comment]
![annotated-awards](https://user-images.githubusercontent.com/25487/30180787-167270fa-93df-11e7-9bd4-1bd48031dfcd.png)

**Comment by mongmedia** [comment]
![mobile-awards](https://user-images.githubusercontent.com/25487/31558676-ec131234-b01b-11e7-991f-5c476becf043.png)
