### ISSUE TITLE
Review Keyboard Accessibility

### ISSUE THREAD

**Issue by mongmedia** [YaleDHLab/dhlab-site#411]
- [ ] For the TabIndex behavior, the tab jumps to the DHLab mark and then disappears when testing on Chrome (v64, MacOS 13.3) Please let me know if there is a better approach to coding the tabindex. Thanks!

- [ ] Make it possible to open dropdown menus w/ keyboard tab

**Comment by duhaime** [comment]
This is now done! Nav submenus are keyboard-navigable on each route's index page; e.g. the opportunities subpages are navigable on the /opportunities.html page...
