### ISSUE TITLE
Jobs Landing Page*

### ISSUE THREAD

**Issue by duhaime** [YaleDHLab/dhlab-site#42]

**Comment by mongmedia** [comment]
I consider this to be a News page view filtered by category. So essentially, it's a View by Category page type. 

![annotated-jobs-category-view](https://user-images.githubusercontent.com/25487/30224712-d0ea3fc6-949d-11e7-8c35-097aa47a3c2e.png)

**Comment by mongmedia** [comment]
![mobile-categoryview](https://user-images.githubusercontent.com/25487/31908439-e2a85d6c-b804-11e7-8f29-4a984e457585.png)
