### ISSUE TITLE
Opportunities Detail Page*

### ISSUE THREAD

**Issue by duhaime** [YaleDHLab/dhlab-site#44]

**Comment by mongmedia** [comment]
![annotated-pd-opp](https://user-images.githubusercontent.com/25487/30215863-4fc49cfc-947f-11e7-9d0e-4725ab47bfa0.png)

**Comment by mongmedia** [comment]
![mobile-opportuities](https://user-images.githubusercontent.com/25487/31559101-7b420a7c-b01d-11e7-912b-52b604a541a1.png)

**Comment by duhaime** [comment]
This is done
