### ISSUE TITLE
Navigation Tablet/Mobile views*

### ISSUE THREAD

**Issue by duhaime** [YaleDHLab/dhlab-site#45]

**Comment by mongmedia** [comment]
![mobile-home](https://user-images.githubusercontent.com/25487/30340150-8ce1510a-97bf-11e7-99b2-55ff180b774f.png)

![footer-mobile](https://user-images.githubusercontent.com/25487/30340140-840fa144-97bf-11e7-9a70-d593e62df7eb.png)

**Comment by mongmedia** [comment]
Mobile: Events
![mobile-events](https://user-images.githubusercontent.com/25487/30340231-c9be8fca-97bf-11e7-80e8-f6cc1a0eb1b0.png)

**Comment by mongmedia** [comment]
![mobile-about](https://user-images.githubusercontent.com/25487/30340243-d2009b10-97bf-11e7-8f9d-96ecc51c7e76.png)

**Comment by mongmedia** [comment]
![mobile-news](https://user-images.githubusercontent.com/25487/30340248-da13040a-97bf-11e7-9adc-6d17d3aeb503.png)

![mobile-news-story](https://user-images.githubusercontent.com/25487/30340252-dd0a687e-97bf-11e7-87f2-6256dc84ff29.png)

**Comment by mongmedia** [comment]
![mobile-menu-open](https://user-images.githubusercontent.com/25487/30600820-6ec78ff8-9d2e-11e7-8355-f03a9d5e2335.png)
![mobile-menu](https://user-images.githubusercontent.com/25487/30600818-6ec29a98-9d2e-11e7-86f1-120a19ef6fa1.png)

These are comps of the mobile menu that opens up for smalls screen sizes. @cderose: Below the main nav links are a few quick links. What three links do you think users would find most helpful? I'm imagining scenarios where newcomers/students are checking on their phones to attends an event or offices hours. What other scenarios do you commonly hear questions about?

**Comment by cderose** [comment]
The three you've listed look great to me, @mongmedia, and cover the majority of newcomer questions we get. Funding opportunities is popular, too, but I don't think I'd want to take away something to put that in - it doesn't lend itself as well to breezy phone searches.
