### ISSUE TITLE
Resources Detail Page*

### ISSUE THREAD

**Issue by duhaime** [YaleDHLab/dhlab-site#46]

**Comment by mongmedia** [comment]
![annotated-whatweoffer](https://user-images.githubusercontent.com/25487/30224807-25aae63c-949e-11e7-950b-92cf096f0d17.png)

**Comment by duhaime** [comment]
@mongmedia I think this is a duplicate of the other resources landing page--could you please edit the images to make them show the resources detail page? I'm guessing it's similar to guides/methods detail pages, but want to be sure...
