### ISSUE TITLE
Event Display

### ISSUE THREAD

**Issue by mongmedia** [YaleDHLab/dhlab-site#478]
Hi, @duhaime: On the home page, when we have less than three future events, let's populate the remaining open slots w/ the most recent past events so that we have the three slots filled at all times. Currently, we have only one future event so our home page looks like this:

<img width="1164" alt="screenshot 2018-04-25 13 07 50" src="https://user-images.githubusercontent.com/25487/39261182-b0b827d6-4889-11e8-9ab8-0b03f84b5397.png">

Thanks,
Monica

**Comment by cderose** [comment]
All set! I updated index.html so that the most recent three events always show.
