### ISSUE TITLE
Create template for recurring events

### ISSUE THREAD

**Issue by cderose** [YaleDHLab/dhlab-site#596]
Create a new template for recurring events (for example - Software Carpentry workshops and the Python working group meetings)

**Comment by mongmedia** [comment]
For events w/ multiple dates, I envision a way of entering the dates, either a range of dates for multiple day workshops or also recurring dates, i.e. weekly dates. I see the date in the corner automatically updating once the earlier date expires.

We can list the events weekly like this:
<img width="240" alt="screenshot 2018-11-07 15 39 17" src="https://user-images.githubusercontent.com/25487/48160139-11263d00-e2a5-11e8-9d73-15ab7470307f.png">

Or like this for multiple dates:
<img width="319" alt="screenshot 2018-11-07 16 03 48" src="https://user-images.githubusercontent.com/25487/48160769-c3123900-e2a6-11e8-9c79-8ed1c6ef7924.png">

**Comment by cderose** [comment]
These look great to me, @mongmedia. 

@duhaime, what do you think?

**Comment by duhaime** [comment]
Yes, looks good!

**Comment by cderose** [comment]
Great! @duhaime, is this something you could implement whenever there's downtime? There's no time crunch.

**Comment by duhaime** [comment]
I certainly could ;) Would you want to take a crack at it though? It could be a fun little challenge. If you don't want to try it out I'm happy to take care of this

**Comment by cderose** [comment]
Sure, I'll give it a try! :)

**Comment by cderose** [comment]
It's a deal!

**Comment by jakekara** [comment]
@cderose Added a new branch that appears to be working but still needs some testing:  iss596-recurring-events

I added a dates array to the recurring python working group as an example. When provided, the dates array is used, a "future event" is anything with at least one date in the future. The date displayed is the next future date, or the last date in the past if there are not future dates. If dates is not provided, date will be used instead.

**Comment by cderose** [comment]
@jakekara This is fantastic! All seems to be working well with the latest branch, so I've gone ahead and merged it. Thanks very much!
