### ISSUE TITLE
Updated Personnel Page: Post-Docs / Fellows

### ISSUE THREAD

**Issue by mongmedia** [YaleDHLab/dhlab-site#65]
Per a conversation w/ Cathy, I have updated the bottom section of the Personnel Listing page type so that it is a bit easier to list past fellow or postdoc associates with some more detail. 

Let me know what you think and I can take a stab at reworking this too in CSS/Jekyll.

Best,
Monica

![updated-personnel-list](https://user-images.githubusercontent.com/25487/30863820-00c5d65a-a2a0-11e7-93df-39ff2d608d44.png)

**Comment by duhaime** [comment]
@mongmedia It looks like the only region of the page affected is the bottom section, right? In the html template, making this modification would mean removing the line:

```
include text/half-width/two_column_text.html
```

toward the bottom of this page: https://github.com/YaleDHLab/dhlab-site/blob/master/_opportunities/postdoctoral-associates.md

If you want to try putting this together that's great, else I'm happy to knock it out.
