### ISSUE TITLE
Project Display

### ISSUE THREAD

**Issue by mongmedia** [YaleDHLab/dhlab-site#68]
I think I've identified the three project "types" that we will be displaying on the site.

1) DHLab type: this will organize DHLab website onto the main project gallery page
2) Archive type: projects that are labeled "archive" will be shown in the archive carousel for work that pre-dates the founding of the DHLab
3) Funded: This identifies projects that have been funded by DHLab grants that we highlight in the carousel at the bottom of grant application pages

**Comment by duhaime** [comment]
The only catch I see is that the projects page has two sections: one for non-funded && non-archived projects, and another for archived projects. Should we add another section for funded projects?

**Comment by mongmedia** [comment]
Thanks for your question. Let's think of the DHLab projects as our main project category. A secondary project category will be Archives. For funded projects, would it work if that was simply a tag that we assigned to the projects where this applies? When I think of "types" it's more of a way of describing the kinds of groupings that some of the includes might display. If we can pull funded projects via tag for the include that appears on the grant opportunities pages, that would be useful.

**Comment by duhaime** [comment]
Closing because this is a no-op
