### ISSUE TITLE
Search Results View

### ISSUE THREAD

**Issue by duhaime** [YaleDHLab/dhlab-site#89]
The mobile nav has a search box, so we should mock up a search results view for desktop and devices...

**Comment by mongmedia** [comment]
Updating location of search in mobile menu and also posting search result views...


![mobile-menu-open](https://user-images.githubusercontent.com/25487/32228807-a76d0dd4-be25-11e7-8309-e672c8de18db.png)
![mobile-menu](https://user-images.githubusercontent.com/25487/32228809-a777c30a-be25-11e7-9d93-9901d16a084d.png)

![mobile-search](https://user-images.githubusercontent.com/25487/32228819-abe0eeee-be25-11e7-8881-0c0f7fcb77ee.png)

**Comment by mongmedia** [comment]
![searchresults](https://user-images.githubusercontent.com/25487/32229201-a6f6d726-be26-11e7-912e-e28487635933.png)
