### ISSUE TITLE
Home Page*

### ISSUE THREAD

**Issue by mongmedia** [YaleDHLab/dhlab-site#9]
![annotated - home](https://user-images.githubusercontent.com/25487/30116074-8c2f736a-92ea-11e7-908a-4469bf29a5c9.png)

This is the desktop view at 1024 px wide

The Home Page has four main section outside of the nav header and footer.
1) The top section will have a hero image/video in the background and focus users on the button "What is Digital Humanities" to connect w/ visitors new to DH. The video background will have a 16:9 aspect ratio.

2) Events Feed: This events feed will show the three next upcoming events. This includes workshops as well as talks and other events hosted by the DHLab. The "events calendar" heading will link directly to a page that lists our events. The category headings above each event is also clickable in that if users click on "Workshops" then they will jump to a category view of Events that shows only workshops. Each event image is approximately 250 x 250 px.

3) What's New: This news feed will show a news story that the admin marks as "featured." "What's New" will jump to the landing page for News stories. The news headline and/or image will jump to the story. The category heading above the news headline is a category link for the news that filters to stories marked w/ the same category. Beneath the headline image, there will be a call to action to subscribe to the newsletter - this is fixed and will not change.

4) Spotlight: This content area just focuses on either dynamic or static pages on the site that we just want to emphasize. It might point to a current project or highlight new personnel or maybe bring attention to a forthcoming deadline. The UX is such that the admin should be able to identify a content link and featured image. Next to the spotlight content will be a box that focuses on Office Hours information, which can be manually updated when needed.  Beneath the image area, we will have a link for how to get started on DH projects.

**Comment by mongmedia** [comment]
![home-page tallerhero](https://user-images.githubusercontent.com/25487/29230987-5881f2e0-7eb3-11e7-8d71-3f0ea90b0d59.png)

This is a variation of the home page w/ a taller hero image. Some feedback suggested that the shorter one felt more like a decorative header rather. My hope is that this area is utilized as a place w/ moving videos that show users what we do as well as the new space but also points to the question "What is DH?" and encourages new visitors to that part of the site.

**Comment by mongmedia** [comment]
![ipad-home](https://user-images.githubusercontent.com/25487/29367442-e917d68e-826a-11e7-8ba2-33a15484b47b.png)

As the window size reduces, the hero image shrinks and the navigation collapses into the menu icon. The headlines reduce from 24 pt to 18 pt.

Events Calendar: The titles w/ overlays drop the category field and the title background snaps to 100% of the image width and about 50% of its previous size.

What's New will still be 100% with and also have the title drop its category tag.
Spotlight will include the story and office hours at 2 blocks that occupy 50% of the screen width.

A Newsletter block will appear below w/ a field for subscribing.
The footer will shrink in width. The 2 columns of info will be laid out as 2 columns.

**Comment by mongmedia** [comment]
![mobile-home](https://user-images.githubusercontent.com/25487/29368283-41186a18-826d-11e7-8189-afa42c8545df.png)

Home - Mobile View:

The main shift is that the event display switches to the mobile version, whereby the event image is 200 x 200 px on the left with the rest of the width as a right column w/ black background with a Title and event info below. 

The content areas like the Spotlight and Office Hours will stack. The footer for mobile will have a row of touchable icons that quickly connect users to phone/email/facebook, etc.

**Comment by duhaime** [comment]
This is done
